### ISSUE TITLE
Optimize Kalman filter parameters (esp. uncertainty matrix)

### ISSUE THREAD

**Issue by flonix8** [starwit/object-tracker#6]
Preliminary testing shows that Kalman tracker parameters are not optimal for our use case.
It should be investigated, if we can upstream some changes to Boxmot repository.

**Comment by edblu1** [comment]
After thoroughly testing and investigating the suboptimal tracking performance of the Kalman filter in certain situations, we found that the filter's parameters weren't ideal, especially at our lower frame rate configurations. To address this, we submitted [a pull request](https://github.com/mikel-brostrom/boxmot/pull/1484)  to the Boxmot repository that allows us to adjust the Uncertainty Matrix (Q) of the Kalman filter. This change now offers the possibility to manually adjust the Kalman filter to counteract the too rigid predictions in dynamic scenes with lower frame rates.
